---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Deploy main nginx.conf (known-good)
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: validate nginx

- name: Ensure nginx enabled & running
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy upgrade map (http context)
  template:
    src: 00-upgrade-map.conf.j2
    dest: /etc/nginx/conf.d/00-upgrade-map.conf
    owner: root
    group: root
    mode: '0644'
  notify: validate nginx

- name: Deploy www9 vhost
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/www9.conf
    owner: root
    group: root
    mode: '0644'
  notify: validate nginx

- name: Remove legacy/conflicting vhosts
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/conf.d/web9.conf
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/site.conf
  notify: validate nginx
