---
- name: Ensure nginx installed
  package:
    name: nginx
    state: present

- name: Ensure nginx enabled & running
  service:
    name: nginx
    state: started
    enabled: true

# Remove built-in default server in nginx.conf (avoids :80 conflicts)
- name: Remove built-in default HTTP server block from nginx.conf
  replace:
    path: /etc/nginx/nginx.conf
    regexp: 'server\s*\{[^}]*server_name\s+_;\s*[^}]*\}\s*\n'
    replace: ''
  notify: validate nginx

# Deploy http{} map
- name: Deploy upgrade map (http context)
  template:
    src: 00-upgrade-map.conf.j2
    dest: /etc/nginx/conf.d/00-upgrade-map.conf
    owner: root
    group: root
    mode: '0644'
  notify: validate nginx

# Deploy canonical vhost
- name: Deploy www9 vhost
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/www9.conf
    owner: root
    group: root
    mode: '0644'
  notify: validate nginx

# Remove legacy/conflicting vhosts
- name: Remove legacy/conflicting vhosts
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/conf.d/web9.conf
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/site.conf
  notify: validate nginx
