# vhost basics
server_name: www9.htf25.qubr.be

# your cert is under a *different* name right now:
# /etc/letsencrypt/live/www9.htf25.qubr.be/...
cert_cn: www9.htf25.qubr.be

upstream_host: 127.0.0.1
upstream_port: 8080
listen_http: 80
listen_https: 443

enable_hsts: true
hsts_max_age: 31536000

manage_firewalld: true
firewalld_zone: public

# Open standard services
firewalld_services:
  - http
  - https

# Optional extra ports (host-level), e.g. SSH if you want bastion-only
firewalld_ports: []   # e.g. ["22/tcp"]

# Optional: restrict to specific sources (rich rules). Leave empty for any.
firewalld_sources: [] # e.g. ["10.1.9.4/32"]
